#!/bin/sh

# remapping of console is gentoo specific and should be done manually 

CONFIG_FOLDER=~/customisations

# sh stuff

cp -v $CONFIG_FOLDER/sh/.profile ~/.profile

# update bash stuff
#cp -v ~/customisations/bash/.bash_profile ~/.bash_profile
#cp -v ~/customisations/bash/.bashrc ~/.bashrc

# update fish stuff
cp -v -r ~/customisations/fish ~/.config/ 

# update tmux stuff
cp -v ~/customisations/tmux/.tmux.conf ~/.tmux.conf

# update vise stuff
cp -v -r $CONFIG_FOLDER/vis ~/.config/ 

# update vim stuff
cp -v ~/customisations/vim/.vimrc ~/.vimrc

# update nvim stuff
#cp -v -r ~/customisations/nvim ~/.config/

# update alacritty stuff
#cp -v ~/customisations/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml 

# update w3m stuff
#not yet implemented
# update irssi?
#not yet implemented

# update amfora stuff
cp -v ~/customisations/amfora/config.toml ~/.config/amfora
cp -v ~/customisations/amfora/newtab.gmi ~/.config/amfora

# update the configs for the most important software on my system. Nethack.
cp -v ~/customisations/nethack/.nethackrc ~/.nethackrc 
