#!/bin/sh
# USE TO MOVE STORED CONFIGS TO SYSTEM

# remapping of console is gentoo specific and should be done manually 

CONFIG_FOLDER=~/configs

# sh stuff

cp -vi $CONFIG_FOLDER/sh/.profile ~/.profile

# update bash stuff
#cp -vi ~/customisations/bash/.bash_profile ~/.bash_profile
#cp -vi ~/customisations/bash/.bashrc ~/.bashrc

# update fish stuff
cp -vi -r $CONFIG_FOLDER/fish ~/.config/ 

# update tmux stuff
#cp -vi $config_fOLDER/tmux/.tmux.conf ~/.tmux.conf

# update vis stuff
cp -vi -r $CONFIG_FOLDER/vis ~/.config/ 

# update vim stuff
cp -vi $CONFIG_FOLDER/vim/.vimrc ~/.vimrc

# update nvim stuff
#cp -vi -r ~/customisations/nvim ~/.config/

# update alacritty stuff
cp -vi $CONFIG_FOLDER/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml 

#xmonad
cp -vi $CONFIG_FOLDER/xmonad/xmonad.hs ~/.xmonad/xmonad.hs 
cp -vi $CONFIG_FOLDER/xmonad/.xmobarrc ~/.xmobarrc

# awesome
cp -vir $CONFIG_FOLDER/awesome ~/.config/

#emacs
#cp -vi $CONFIG_FOLDER/emacs/init.el ~/.emacs.d/init.el

# update w3m stuff
#not yet implemented
# update irssi?
#not yet implemented

# update amfora stuff
cp -vi $CONFIG_FOLDER/amfora/config.toml ~/.config/amfora
cp -vi $CONFIG_FOLDER/amfora/newtab.gmi ~/.config/amfora

# update the configs for the most important software on my system. Nethack.
cp -vi $CONFIG_FOLDER/nethack/.nethackrc ~/.nethackrc 
