#!/bin/bash

# remapping was a one-off static thing, no need to update

# update bash stuff
cp -v ~/.bash_profile ~/.bashrc ~/customisations/bash

# update fish stuff

cp -v ~/.config/fish/* ~/customisations/fish

# update tmux stuff
cp -v ~/.tmux.conf ~/customisations/tmux #tmux.batt is also static

# update vim stuff
cp -v ~/.vimrc ~/customisations/vim

# update nvim stuff

cp -v ~/.config/nvim/* ~/customisations/nvim
# update w3m stuff

# update irssi?

# update the configs for the most important software on my system. Nethack.
cp -v ~/.nethackrc ~/customisations/nethack
