#!/bin/sh

# remapping was a one-off static thing, no need to update

CONFIG_FOLDER=~/customisations

# update sh stuff
cp -v ~/.profile $CONFIG_FOLDER/sh

# update bash stuff
#cp -v ~/.bash_profile ~/.bashrc ~/customisations/bash

# update fish stuff
cp -v ~/.config/fish/* ~/customisations/fish

# update tmux stuff
cp -v ~/.tmux.conf ~/customisations/tmux #tmux.batt is also static

# update vis stuff
cp -v ~/.config/vis/* $CONFIG_FOLDER/vis

# update vim stuff
cp -v ~/.vimrc ~/customisations/vim

# update nvim stuff
#cp -v ~/.config/nvim/* ~/customisations/nvim

# update alacritty stuff
#cp -v ~/.config/alacritty/alacritty.yml ~/customisations/alacritty

# update w3m stuff
#not yet implemented
# update irssi?
#not yet implemented

# update amfora stuff
cp -v ~/.config/amfora/config.toml ~/customisations/amfora
cp -v ~/.config/amfora/newtab.gmi ~/customisations/amfora

# update the configs for the most important software on my system. Nethack.
cp -v ~/.nethackrc ~/customisations/nethack
